
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Dec 27 2023 19:09:09 IST (Dec 27 2023 13:39:09 UTC)

// Verification Directory fv/uart_top 

module uartrx_clk_freq1000000_baud_rate9600(clk, rst, rx, done, rxdata);
  input clk, rst, rx;
  output done;
  output [7:0] rxdata;
  wire clk, rst, rx;
  wire done;
  wire [7:0] rxdata;
  wire [31:0] count;
  wire [31:0] counts;
  wire [1:0] state;
  wire inc_add_153_24_n_317, inc_add_153_24_n_318,
       inc_add_153_24_n_320, inc_add_153_24_n_323,
       inc_add_153_24_n_328, inc_add_153_24_n_330,
       inc_add_153_24_n_332, inc_add_153_24_n_335;
  wire inc_add_153_24_n_338, inc_add_153_24_n_343,
       inc_add_153_24_n_345, inc_add_153_24_n_347,
       inc_add_153_24_n_349, inc_add_153_24_n_355,
       inc_add_153_24_n_357, inc_add_153_24_n_360;
  wire inc_add_153_24_n_362, inc_add_153_24_n_363,
       inc_add_153_24_n_367, inc_add_153_24_n_369,
       inc_add_153_24_n_372, inc_add_153_24_n_373,
       inc_add_153_24_n_376, inc_add_153_24_n_378;
  wire inc_add_153_24_n_379, inc_add_153_24_n_381,
       inc_add_153_24_n_382, inc_add_153_24_n_383,
       inc_add_153_24_n_387, inc_add_153_24_n_388,
       inc_add_153_24_n_392, inc_add_153_24_n_395;
  wire inc_add_153_24_n_400, inc_add_153_24_n_402,
       inc_add_153_24_n_405, inc_add_153_24_n_408,
       inc_add_153_24_n_409, inc_add_153_24_n_410,
       inc_add_153_24_n_412, inc_add_153_24_n_415;
  wire inc_add_153_24_n_416, inc_add_153_24_n_419,
       inc_add_153_24_n_429, inc_add_153_24_n_437,
       inc_add_153_24_n_445, inc_add_190_23_n_223,
       inc_add_190_23_n_226, inc_add_190_23_n_229;
  wire inc_add_190_23_n_231, inc_add_190_23_n_233,
       inc_add_190_23_n_235, inc_add_190_23_n_237,
       inc_add_190_23_n_239, inc_add_190_23_n_241,
       inc_add_190_23_n_243, inc_add_190_23_n_245;
  wire inc_add_190_23_n_247, inc_add_190_23_n_249,
       inc_add_190_23_n_251, inc_add_190_23_n_253,
       inc_add_190_23_n_255, inc_add_190_23_n_257,
       inc_add_190_23_n_259, inc_add_190_23_n_261;
  wire inc_add_190_23_n_263, inc_add_190_23_n_265,
       inc_add_190_23_n_267, inc_add_190_23_n_269,
       inc_add_190_23_n_271, inc_add_190_23_n_273,
       inc_add_190_23_n_275, inc_add_190_23_n_277;
  wire inc_add_190_23_n_279, inc_add_190_23_n_281,
       inc_add_190_23_n_283, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_26, n_27, n_28, n_29, n_31, n_32;
  wire n_33, n_35, n_36, n_37, n_39, n_40, n_41, n_43;
  wire n_44, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_135;
  wire n_137, n_138, n_139, n_141, n_143, n_144, n_145, n_147;
  wire n_148, n_149, n_151, n_152, n_153, n_155, n_156, n_157;
  wire n_159, n_160, n_161, n_163, n_164, n_165, n_167, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, uclk;
  dfnrq1 \count_reg[0] (.CP (clk), .D (n_37), .Q (count[0]));
  dfnrq1 \count_reg[1] (.CP (clk), .D (n_47), .Q (count[1]));
  dfnrq1 \count_reg[2] (.CP (clk), .D (n_172), .Q (count[2]));
  dfnrq1 \count_reg[3] (.CP (clk), .D (n_50), .Q (count[3]));
  dfnrq1 \count_reg[5] (.CP (clk), .D (n_51), .Q (count[5]));
  dfnrq1 \count_reg[6] (.CP (clk), .D (n_173), .Q (count[6]));
  dfnrq1 \count_reg[7] (.CP (clk), .D (n_49), .Q (count[7]));
  dfnrq1 \count_reg[8] (.CP (clk), .D (n_44), .Q (count[8]));
  dfnrq1 \count_reg[9] (.CP (clk), .D (n_43), .Q (count[9]));
  dfnrq1 \count_reg[10] (.CP (clk), .D (n_174), .Q (count[10]));
  dfnrq1 \count_reg[11] (.CP (clk), .D (n_40), .Q (count[11]));
  dfnrq1 \count_reg[12] (.CP (clk), .D (n_41), .Q (count[12]));
  dfnrq1 \count_reg[13] (.CP (clk), .D (n_39), .Q (count[13]));
  dfnrq1 \count_reg[14] (.CP (clk), .D (n_175), .Q (count[14]));
  dfnrq1 \count_reg[15] (.CP (clk), .D (n_52), .Q (count[15]));
  dfnrq1 \count_reg[16] (.CP (clk), .D (n_21), .Q (count[16]));
  dfnrq1 \count_reg[17] (.CP (clk), .D (n_35), .Q (count[17]));
  dfnrq1 \count_reg[18] (.CP (clk), .D (n_176), .Q (count[18]));
  dfnrq1 \count_reg[19] (.CP (clk), .D (n_33), .Q (count[19]));
  dfnrq1 \count_reg[21] (.CP (clk), .D (n_31), .Q (count[21]));
  dfnrq1 \count_reg[22] (.CP (clk), .D (n_177), .Q (count[22]));
  dfnrq1 \count_reg[23] (.CP (clk), .D (n_29), .Q (count[23]));
  dfnrq1 \count_reg[24] (.CP (clk), .D (n_28), .Q (count[24]));
  dfnrq1 \count_reg[26] (.CP (clk), .D (n_179), .Q (count[26]));
  dfnrq1 \count_reg[27] (.CP (clk), .D (n_26), .Q (count[27]));
  dfnrq1 \count_reg[28] (.CP (clk), .D (n_178), .Q (count[28]));
  dfnrq1 \count_reg[29] (.CP (clk), .D (n_23), .Q (count[29]));
  dfnrq1 \count_reg[31] (.CP (clk), .D (n_36), .Q (count[31]));
  dfnrq1 \counts_reg[0] (.CP (uclk), .D (n_93), .Q (counts[0]));
  dfnrq1 \counts_reg[1] (.CP (uclk), .D (n_91), .Q (counts[1]));
  dfnrq1 \counts_reg[2] (.CP (uclk), .D (n_95), .Q (counts[2]));
  dfnrq1 \counts_reg[3] (.CP (uclk), .D (n_94), .Q (counts[3]));
  dfnrq1 \counts_reg[4] (.CP (uclk), .D (n_92), .Q (counts[4]));
  dfnrq1 \counts_reg[5] (.CP (uclk), .D (n_90), .Q (counts[5]));
  dfnrq1 \counts_reg[6] (.CP (uclk), .D (n_89), .Q (counts[6]));
  dfnrq1 \counts_reg[7] (.CP (uclk), .D (n_88), .Q (counts[7]));
  dfnrq1 \counts_reg[8] (.CP (uclk), .D (n_87), .Q (counts[8]));
  dfnrq1 \counts_reg[9] (.CP (uclk), .D (n_86), .Q (counts[9]));
  dfnrq1 \counts_reg[10] (.CP (uclk), .D (n_83), .Q (counts[10]));
  dfnrq1 \counts_reg[11] (.CP (uclk), .D (n_85), .Q (counts[11]));
  dfnrq1 \counts_reg[12] (.CP (uclk), .D (n_84), .Q (counts[12]));
  dfnrq1 \counts_reg[13] (.CP (uclk), .D (n_82), .Q (counts[13]));
  dfnrq1 \counts_reg[14] (.CP (uclk), .D (n_81), .Q (counts[14]));
  dfnrq1 \counts_reg[15] (.CP (uclk), .D (n_80), .Q (counts[15]));
  dfnrq1 \counts_reg[16] (.CP (uclk), .D (n_79), .Q (counts[16]));
  dfnrq1 \counts_reg[17] (.CP (uclk), .D (n_78), .Q (counts[17]));
  dfnrq1 \counts_reg[18] (.CP (uclk), .D (n_77), .Q (counts[18]));
  dfnrq1 \counts_reg[19] (.CP (uclk), .D (n_76), .Q (counts[19]));
  dfnrq1 \counts_reg[20] (.CP (uclk), .D (n_75), .Q (counts[20]));
  dfnrq1 \counts_reg[21] (.CP (uclk), .D (n_74), .Q (counts[21]));
  dfnrq1 \counts_reg[22] (.CP (uclk), .D (n_73), .Q (counts[22]));
  dfnrq1 \counts_reg[23] (.CP (uclk), .D (n_72), .Q (counts[23]));
  dfnrq1 \counts_reg[24] (.CP (uclk), .D (n_71), .Q (counts[24]));
  dfnrq1 \counts_reg[25] (.CP (uclk), .D (n_70), .Q (counts[25]));
  dfnrq1 \counts_reg[26] (.CP (uclk), .D (n_69), .Q (counts[26]));
  dfnrq1 \counts_reg[27] (.CP (uclk), .D (n_67), .Q (counts[27]));
  dfnrq1 \counts_reg[28] (.CP (uclk), .D (n_68), .Q (counts[28]));
  dfnrq1 \counts_reg[29] (.CP (uclk), .D (n_66), .Q (counts[29]));
  dfnrq1 \counts_reg[30] (.CP (uclk), .D (n_171), .Q (counts[30]));
  dfnrq1 \counts_reg[31] (.CP (uclk), .D (n_64), .Q (counts[31]));
  dfnrq1 done_reg(.CP (uclk), .D (n_0), .Q (done));
  dfnrq1 \rxdata_reg[0] (.CP (uclk), .D (n_97), .Q (rxdata[0]));
  dfnrq1 \rxdata_reg[1] (.CP (uclk), .D (n_98), .Q (rxdata[1]));
  dfnrq1 \rxdata_reg[2] (.CP (uclk), .D (n_99), .Q (rxdata[2]));
  dfnrq1 \rxdata_reg[3] (.CP (uclk), .D (n_100), .Q (rxdata[3]));
  dfnrq1 \rxdata_reg[4] (.CP (uclk), .D (n_101), .Q (rxdata[4]));
  dfnrq1 \rxdata_reg[5] (.CP (uclk), .D (n_102), .Q (rxdata[5]));
  dfnrq1 \rxdata_reg[6] (.CP (uclk), .D (n_103), .Q (rxdata[6]));
  dfnrq1 \rxdata_reg[7] (.CP (uclk), .D (n_104), .Q (rxdata[7]));
  aor22d1 g3212__8780(.A1 (n_62), .A2 (rxdata[7]), .B1 (n_61), .B2
       (rx), .Z (n_104));
  aor22d1 g3213__4296(.A1 (n_62), .A2 (rxdata[6]), .B1 (n_61), .B2
       (rxdata[7]), .Z (n_103));
  aor22d1 g3214__3772(.A1 (n_62), .A2 (rxdata[5]), .B1 (n_61), .B2
       (rxdata[6]), .Z (n_102));
  aor22d1 g3215__1474(.A1 (n_62), .A2 (rxdata[4]), .B1 (n_61), .B2
       (rxdata[5]), .Z (n_101));
  aor22d1 g3216__4547(.A1 (n_62), .A2 (rxdata[3]), .B1 (n_61), .B2
       (rxdata[4]), .Z (n_100));
  aor22d1 g3217__9682(.A1 (n_62), .A2 (rxdata[2]), .B1 (n_61), .B2
       (rxdata[3]), .Z (n_99));
  aor22d1 g3219__2683(.A1 (n_62), .A2 (rxdata[1]), .B1 (n_61), .B2
       (rxdata[2]), .Z (n_98));
  aor22d1 g3221__1309(.A1 (n_62), .A2 (rxdata[0]), .B1 (n_61), .B2
       (rxdata[1]), .Z (n_97));
  oai31d1 g3222__6877(.A (n_63), .B1 (rst), .B2 (rx), .B3 (state[0]),
       .ZN (n_96));
  an02d1 g3233__2900(.A1 (n_61), .A2 (n_106), .Z (n_95));
  an02d1 g3234__2391(.A1 (n_61), .A2 (n_107), .Z (n_94));
  nr02d0 g3235__7675(.A1 (n_60), .A2 (counts[0]), .ZN (n_93));
  an02d1 g3236__7118(.A1 (n_61), .A2 (n_108), .Z (n_92));
  an02d1 g3237__8757(.A1 (n_61), .A2 (n_105), .Z (n_91));
  an02d1 g3238__1786(.A1 (n_61), .A2 (n_109), .Z (n_90));
  an02d1 g3239__5953(.A1 (n_61), .A2 (n_110), .Z (n_89));
  an02d1 g3240__5703(.A1 (n_61), .A2 (n_111), .Z (n_88));
  an02d1 g3241__7114(.A1 (n_61), .A2 (n_112), .Z (n_87));
  an02d1 g3242__5266(.A1 (n_61), .A2 (n_113), .Z (n_86));
  an02d1 g3243__2250(.A1 (n_61), .A2 (n_115), .Z (n_85));
  an02d1 g3244__6083(.A1 (n_61), .A2 (n_116), .Z (n_84));
  an02d1 g3245__2703(.A1 (n_61), .A2 (n_114), .Z (n_83));
  an02d1 g3246__5795(.A1 (n_61), .A2 (n_117), .Z (n_82));
  an02d1 g3247__7344(.A1 (n_61), .A2 (n_118), .Z (n_81));
  an02d1 g3248__1840(.A1 (n_61), .A2 (n_119), .Z (n_80));
  an02d1 g3249__5019(.A1 (n_61), .A2 (n_120), .Z (n_79));
  an02d1 g3250__1857(.A1 (n_121), .A2 (n_61), .Z (n_78));
  an02d1 g3251__9906(.A1 (n_122), .A2 (n_61), .Z (n_77));
  an02d1 g3252__8780(.A1 (n_123), .A2 (n_61), .Z (n_76));
  an02d1 g3253__4296(.A1 (n_124), .A2 (n_61), .Z (n_75));
  an02d1 g3254__3772(.A1 (n_125), .A2 (n_61), .Z (n_74));
  an02d1 g3255__1474(.A1 (n_126), .A2 (n_61), .Z (n_73));
  an02d1 g3256__4547(.A1 (n_127), .A2 (n_61), .Z (n_72));
  an02d1 g3257__9682(.A1 (n_128), .A2 (n_61), .Z (n_71));
  an02d1 g3258__2683(.A1 (n_129), .A2 (n_61), .Z (n_70));
  an02d1 g3259__1309(.A1 (n_130), .A2 (n_61), .Z (n_69));
  an02d1 g3260__6877(.A1 (n_132), .A2 (n_61), .Z (n_68));
  an02d1 g3261__2900(.A1 (n_131), .A2 (n_61), .Z (n_67));
  an02d1 g3262__2391(.A1 (n_133), .A2 (n_61), .Z (n_66));
  an02d1 g3264__7118(.A1 (n_135), .A2 (n_61), .Z (n_64));
  oai21d1 g3265__8757(.A (state[0]), .B1 (n_59), .B2 (rst), .ZN (n_63));
  nr02d0 g3268__1786(.A1 (n_59), .A2 (n_4), .ZN (n_62));
  inv0d0 g3269(.I (n_60), .ZN (n_61));
  nd02d0 g3270__5953(.A1 (n_59), .A2 (n_5), .ZN (n_60));
  or02d1 g3271__5703(.A1 (n_58), .A2 (counts[31]), .Z (n_59));
  nr04d0 g3272__7114(.A1 (counts[25]), .A2 (counts[30]), .A3
       (counts[24]), .A4 (n_57), .ZN (n_58));
  or04d1 g3273__5266(.A1 (n_56), .A2 (counts[22]), .A3 (counts[21]),
       .A4 (counts[20]), .Z (n_57));
  or04d1 g3274__2250(.A1 (n_55), .A2 (counts[19]), .A3 (counts[18]),
       .A4 (counts[17]), .Z (n_56));
  or04d1 g3275__6083(.A1 (n_53), .A2 (counts[16]), .A3 (counts[14]),
       .A4 (counts[7]), .Z (n_55));
  oai22d1 g3294__2703(.A1 (n_19), .A2 (n_2), .B1 (n_20), .B2 (uclk),
       .ZN (n_54));
  or04d1 g3296__5795(.A1 (n_18), .A2 (counts[6]), .A3 (counts[5]), .A4
       (counts[3]), .Z (n_53));
  an02d0 g3311__7344(.A1 (n_153), .A2 (n_20), .Z (n_52));
  an02d1 g3312__1840(.A1 (n_20), .A2 (n_163), .Z (n_51));
  an02d1 g3313__5019(.A1 (n_20), .A2 (n_165), .Z (n_50));
  an02d1 g3314__1857(.A1 (n_20), .A2 (n_161), .Z (n_49));
  an02d1 g3315__9906(.A1 (n_20), .A2 (n_164), .Z (n_48));
  an02d1 g3316__8780(.A1 (n_20), .A2 (n_167), .Z (n_47));
  an02d1 g3319__1474(.A1 (n_20), .A2 (n_160), .Z (n_44));
  an02d1 g3320__4547(.A1 (n_20), .A2 (n_159), .Z (n_43));
  an02d1 g3322__2683(.A1 (n_20), .A2 (n_156), .Z (n_41));
  an02d0 g3323__1309(.A1 (n_20), .A2 (n_157), .Z (n_40));
  an02d1 g3324__6877(.A1 (n_20), .A2 (n_155), .Z (n_39));
  nr02d1 g3326__2391(.A1 (count[0]), .A2 (n_19), .ZN (n_37));
  an02d1 g3327__7675(.A1 (n_20), .A2 (n_137), .Z (n_36));
  an02d1 g3328__7118(.A1 (n_20), .A2 (n_151), .Z (n_35));
  an02d0 g3330__1786(.A1 (n_149), .A2 (n_20), .Z (n_33));
  an02d1 g3331__5953(.A1 (n_20), .A2 (n_148), .Z (n_32));
  an02d0 g3332__5703(.A1 (n_147), .A2 (n_20), .Z (n_31));
  an02d0 g3334__5266(.A1 (n_145), .A2 (n_20), .Z (n_29));
  an02d0 g3335__2250(.A1 (n_20), .A2 (n_144), .Z (n_28));
  an02d0 g3336__6083(.A1 (n_143), .A2 (n_20), .Z (n_27));
  an02d0 g3337__2703(.A1 (n_141), .A2 (n_20), .Z (n_26));
  an02d0 g3340__1840(.A1 (n_139), .A2 (n_20), .Z (n_23));
  an02d0 g3341__5019(.A1 (n_138), .A2 (n_20), .Z (n_22));
  an02d1 g3342__1857(.A1 (n_20), .A2 (n_152), .Z (n_21));
  inv0d0 g3343(.I (n_20), .ZN (n_19));
  aoim21d1 g3344__9906(.A (n_170), .B1 (n_9), .B2 (count[31]), .ZN
       (n_20));
  or04d1 g3345__8780(.A1 (n_16), .A2 (counts[29]), .A3 (counts[9]), .A4
       (counts[26]), .Z (n_18));
  or04d1 g3347__3772(.A1 (n_12), .A2 (counts[28]), .A3 (counts[11]),
       .A4 (counts[23]), .Z (n_16));
  nr04d1 g3348__1474(.A1 (count[27]), .A2 (count[29]), .A3 (count[28]),
       .A4 (n_13), .ZN (n_15));
  nr04d1 g3349__4547(.A1 (count[17]), .A2 (count[19]), .A3 (count[18]),
       .A4 (n_11), .ZN (n_14));
  or04d0 g3350__9682(.A1 (n_6), .A2 (count[24]), .A3 (count[25]), .A4
       (count[26]), .Z (n_13));
  or04d1 g3351__2683(.A1 (n_8), .A2 (counts[27]), .A3 (counts[4]), .A4
       (counts[12]), .Z (n_12));
  nd23d1 g3352__1309(.A1 (count[11]), .A2 (count[16]), .A3 (n_7), .ZN
       (n_11));
  aoi311d1 g3353__6877(.A (count[8]), .B (count[30]), .C1 (n_3), .C2
       (count[5]), .C3 (count[4]), .ZN (n_10));
  nr04d1 g3354__2900(.A1 (count[12]), .A2 (count[15]), .A3 (count[14]),
       .A4 (count[13]), .ZN (n_9));
  or04d1 g3355__2391(.A1 (counts[13]), .A2 (counts[15]), .A3
       (counts[8]), .A4 (counts[10]), .Z (n_8));
  nr04d1 g3356__7675(.A1 (count[6]), .A2 (count[10]), .A3 (count[9]),
       .A4 (count[7]), .ZN (n_7));
  or04d0 g3357__7118(.A1 (count[21]), .A2 (count[20]), .A3 (count[22]),
       .A4 (count[23]), .Z (n_6));
  inv0d0 g3358(.I (n_5), .ZN (n_4));
  nr02d0 g3359__8757(.A1 (rst), .A2 (n_1), .ZN (n_5));
  or02d0 g3360__1786(.A1 (count[3]), .A2 (count[2]), .Z (n_3));
  aor21d1 g2__5953(.A (n_62), .B1 (n_5), .B2 (done), .Z (n_0));
  oaim22d1 inc_add_153_24_g516__5703(.A1 (inc_add_153_24_n_320), .A2
       (count[27]), .B1 (inc_add_153_24_n_320), .B2 (count[27]), .ZN
       (n_141));
  oaim22d1 inc_add_153_24_g517__7114(.A1 (inc_add_153_24_n_323), .A2
       (count[23]), .B1 (inc_add_153_24_n_323), .B2 (count[23]), .ZN
       (n_145));
  oaim22d1 inc_add_153_24_g518__5266(.A1 (inc_add_153_24_n_317), .A2
       (count[31]), .B1 (inc_add_153_24_n_317), .B2 (count[31]), .ZN
       (n_137));
  oaim22d1 inc_add_153_24_g519__2250(.A1 (inc_add_153_24_n_332), .A2
       (count[19]), .B1 (inc_add_153_24_n_332), .B2 (count[19]), .ZN
       (n_149));
  oaim22d1 inc_add_153_24_g520__6083(.A1 (inc_add_153_24_n_335), .A2
       (count[15]), .B1 (inc_add_153_24_n_335), .B2 (count[15]), .ZN
       (n_153));
  oaim22d1 inc_add_153_24_g521__2703(.A1 (inc_add_153_24_n_349), .A2
       (count[11]), .B1 (inc_add_153_24_n_349), .B2 (count[11]), .ZN
       (n_157));
  oaim22d1 inc_add_153_24_g522__5795(.A1 (inc_add_153_24_n_347), .A2
       (count[29]), .B1 (inc_add_153_24_n_347), .B2 (count[29]), .ZN
       (n_139));
  aoi21d1 inc_add_153_24_g525__5019(.A (inc_add_153_24_n_318), .B1
       (inc_add_153_24_n_338), .B2 (inc_add_153_24_n_419), .ZN (n_138));
  inv0d0 inc_add_153_24_g526(.I (inc_add_153_24_n_317), .ZN
       (inc_add_153_24_n_318));
  nd12d1 inc_add_153_24_g527__1857(.A1 (inc_add_153_24_n_338), .A2
       (count[30]), .ZN (inc_add_153_24_n_317));
  nd02d1 inc_add_153_24_g528__9906(.A1 (inc_add_153_24_n_328), .A2
       (count[26]), .ZN (inc_add_153_24_n_320));
  nd02d1 inc_add_153_24_g529__8780(.A1 (inc_add_153_24_n_330), .A2
       (count[22]), .ZN (inc_add_153_24_n_323));
  ah01d1 inc_add_153_24_g532__1474(.A (inc_add_153_24_n_360), .B
       (count[25]), .CO (inc_add_153_24_n_328), .S (n_143));
  ah01d1 inc_add_153_24_g533__4547(.A (inc_add_153_24_n_362), .B
       (count[21]), .CO (inc_add_153_24_n_330), .S (n_147));
  nd02d1 inc_add_153_24_g534__9682(.A1 (inc_add_153_24_n_343), .A2
       (count[18]), .ZN (inc_add_153_24_n_332));
  nd02d1 inc_add_153_24_g535__2683(.A1 (inc_add_153_24_n_345), .A2
       (count[14]), .ZN (inc_add_153_24_n_335));
  nd03d1 inc_add_153_24_g536__1309(.A1 (inc_add_153_24_n_357), .A2
       (count[29]), .A3 (count[28]), .ZN (inc_add_153_24_n_338));
  ah01d1 inc_add_153_24_g539__2900(.A (inc_add_153_24_n_367), .B
       (count[17]), .CO (inc_add_153_24_n_343), .S (n_151));
  ah01d1 inc_add_153_24_g540__2391(.A (inc_add_153_24_n_369), .B
       (count[13]), .CO (inc_add_153_24_n_345), .S (n_155));
  nd02d1 inc_add_153_24_g542__7675(.A1 (inc_add_153_24_n_357), .A2
       (count[28]), .ZN (inc_add_153_24_n_347));
  nd02d1 inc_add_153_24_g543__7118(.A1 (inc_add_153_24_n_355), .A2
       (count[10]), .ZN (inc_add_153_24_n_349));
  oaim22d1 inc_add_153_24_g544__8757(.A1 (inc_add_153_24_n_373), .A2
       (count[7]), .B1 (inc_add_153_24_n_373), .B2 (count[7]), .ZN
       (n_161));
  ah01d1 inc_add_153_24_g545__1786(.A (inc_add_153_24_n_372), .B
       (count[9]), .CO (inc_add_153_24_n_355), .S (n_159));
  nr02d1 inc_add_153_24_g546__5953(.A1 (inc_add_153_24_n_437), .A2
       (inc_add_153_24_n_363), .ZN (inc_add_153_24_n_357));
  ah01d1 inc_add_153_24_g547__5703(.A (inc_add_153_24_n_379), .B
       (count[24]), .CO (inc_add_153_24_n_360), .S (n_144));
  ah01d1 inc_add_153_24_g548__7114(.A (inc_add_153_24_n_378), .B
       (count[20]), .CO (inc_add_153_24_n_362), .S (n_148));
  nd04d1 inc_add_153_24_g549__5266(.A1 (count[24]), .A2
       (inc_add_153_24_n_379), .A3 (count[27]), .A4 (count[26]), .ZN
       (inc_add_153_24_n_363));
  ah01d1 inc_add_153_24_g550__2250(.A (inc_add_153_24_n_383), .B
       (count[16]), .CO (inc_add_153_24_n_367), .S (n_152));
  ah01d1 inc_add_153_24_g551__6083(.A (inc_add_153_24_n_381), .B
       (count[12]), .CO (inc_add_153_24_n_369), .S (n_156));
  ah01d1 inc_add_153_24_g553__5795(.A (inc_add_153_24_n_387), .B
       (count[8]), .CO (inc_add_153_24_n_372), .S (n_160));
  nd02d1 inc_add_153_24_g554__7344(.A1 (inc_add_153_24_n_376), .A2
       (count[6]), .ZN (inc_add_153_24_n_373));
  ah01d1 inc_add_153_24_g555__1840(.A (inc_add_153_24_n_400), .B
       (count[5]), .CO (inc_add_153_24_n_376), .S (n_163));
  nr02d1 inc_add_153_24_g556__5019(.A1 (inc_add_153_24_n_416), .A2
       (inc_add_153_24_n_382), .ZN (inc_add_153_24_n_378));
  nr03d1 inc_add_153_24_g557__1857(.A1 (inc_add_153_24_n_429), .A2
       (inc_add_153_24_n_395), .A3 (inc_add_153_24_n_382), .ZN
       (inc_add_153_24_n_379));
  nr02d1 inc_add_153_24_g558__9906(.A1 (inc_add_153_24_n_412), .A2
       (inc_add_153_24_n_388), .ZN (inc_add_153_24_n_381));
  inv0d0 inc_add_153_24_g559(.I (inc_add_153_24_n_382), .ZN
       (inc_add_153_24_n_383));
  nd04d1 inc_add_153_24_g560__8780(.A1 (count[12]), .A2
       (inc_add_153_24_n_387), .A3 (inc_add_153_24_n_402), .A4
       (count[13]), .ZN (inc_add_153_24_n_382));
  inv0d0 inc_add_153_24_g561(.I (inc_add_153_24_n_387), .ZN
       (inc_add_153_24_n_388));
  nr02d1 inc_add_153_24_g562__4296(.A1 (inc_add_153_24_n_445), .A2
       (inc_add_153_24_n_392), .ZN (inc_add_153_24_n_387));
  oaim22d1 inc_add_153_24_g563__3772(.A1 (inc_add_153_24_n_405), .A2
       (count[3]), .B1 (inc_add_153_24_n_405), .B2 (count[3]), .ZN
       (n_165));
  nd04d1 inc_add_153_24_g564__1474(.A1 (count[5]), .A2
       (inc_add_153_24_n_409), .A3 (count[7]), .A4 (count[6]), .ZN
       (inc_add_153_24_n_392));
  nd04d1 inc_add_153_24_g565__4547(.A1 (count[21]), .A2
       (inc_add_153_24_n_415), .A3 (count[23]), .A4 (count[22]), .ZN
       (inc_add_153_24_n_395));
  aoi21d1 inc_add_153_24_g566__9682(.A (inc_add_153_24_n_400), .B1
       (inc_add_153_24_n_408), .B2 (inc_add_153_24_n_445), .ZN (n_164));
  nr02d1 inc_add_153_24_g567__2683(.A1 (inc_add_153_24_n_445), .A2
       (inc_add_153_24_n_408), .ZN (inc_add_153_24_n_400));
  nr23d1 inc_add_153_24_g568__1309(.A1 (count[14]), .A2 (count[15]),
       .A3 (inc_add_153_24_n_412), .ZN (inc_add_153_24_n_402));
  nd02d1 inc_add_153_24_g570__2900(.A1 (inc_add_153_24_n_410), .A2
       (count[2]), .ZN (inc_add_153_24_n_405));
  inv0d0 inc_add_153_24_g571(.I (inc_add_153_24_n_408), .ZN
       (inc_add_153_24_n_409));
  nd03d1 inc_add_153_24_g572__2391(.A1 (inc_add_153_24_n_410), .A2
       (count[2]), .A3 (count[3]), .ZN (inc_add_153_24_n_408));
  ah01d1 inc_add_153_24_g573__7675(.A (count[0]), .B (count[1]), .CO
       (inc_add_153_24_n_410), .S (n_167));
  nd04d1 inc_add_153_24_g574__7118(.A1 (count[9]), .A2 (count[10]), .A3
       (count[11]), .A4 (count[8]), .ZN (inc_add_153_24_n_412));
  inv0d0 inc_add_153_24_g575(.I (inc_add_153_24_n_416), .ZN
       (inc_add_153_24_n_415));
  nd04d1 inc_add_153_24_g576__8757(.A1 (count[17]), .A2 (count[18]),
       .A3 (count[19]), .A4 (count[16]), .ZN (inc_add_153_24_n_416));
  oaim22d1 inc_add_190_23_g407__5953(.A1 (inc_add_190_23_n_223), .A2
       (counts[31]), .B1 (inc_add_190_23_n_223), .B2 (counts[31]), .ZN
       (n_135));
  nd02d0 inc_add_190_23_g409__7114(.A1 (inc_add_190_23_n_226), .A2
       (counts[30]), .ZN (inc_add_190_23_n_223));
  ah01d1 inc_add_190_23_g410__5266(.A (inc_add_190_23_n_229), .B
       (counts[29]), .CO (inc_add_190_23_n_226), .S (n_133));
  ah01d1 inc_add_190_23_g411__2250(.A (inc_add_190_23_n_231), .B
       (counts[28]), .CO (inc_add_190_23_n_229), .S (n_132));
  ah01d1 inc_add_190_23_g412__6083(.A (inc_add_190_23_n_233), .B
       (counts[27]), .CO (inc_add_190_23_n_231), .S (n_131));
  ah01d1 inc_add_190_23_g413__2703(.A (inc_add_190_23_n_235), .B
       (counts[26]), .CO (inc_add_190_23_n_233), .S (n_130));
  ah01d1 inc_add_190_23_g414__5795(.A (inc_add_190_23_n_237), .B
       (counts[25]), .CO (inc_add_190_23_n_235), .S (n_129));
  ah01d1 inc_add_190_23_g415__7344(.A (inc_add_190_23_n_239), .B
       (counts[24]), .CO (inc_add_190_23_n_237), .S (n_128));
  ah01d1 inc_add_190_23_g416__1840(.A (inc_add_190_23_n_241), .B
       (counts[23]), .CO (inc_add_190_23_n_239), .S (n_127));
  ah01d1 inc_add_190_23_g417__5019(.A (inc_add_190_23_n_243), .B
       (counts[22]), .CO (inc_add_190_23_n_241), .S (n_126));
  ah01d1 inc_add_190_23_g418__1857(.A (inc_add_190_23_n_245), .B
       (counts[21]), .CO (inc_add_190_23_n_243), .S (n_125));
  ah01d1 inc_add_190_23_g419__9906(.A (inc_add_190_23_n_247), .B
       (counts[20]), .CO (inc_add_190_23_n_245), .S (n_124));
  ah01d1 inc_add_190_23_g420__8780(.A (inc_add_190_23_n_249), .B
       (counts[19]), .CO (inc_add_190_23_n_247), .S (n_123));
  ah01d1 inc_add_190_23_g421__4296(.A (inc_add_190_23_n_251), .B
       (counts[18]), .CO (inc_add_190_23_n_249), .S (n_122));
  ah01d1 inc_add_190_23_g422__3772(.A (inc_add_190_23_n_253), .B
       (counts[17]), .CO (inc_add_190_23_n_251), .S (n_121));
  ah01d1 inc_add_190_23_g423__1474(.A (inc_add_190_23_n_255), .B
       (counts[16]), .CO (inc_add_190_23_n_253), .S (n_120));
  ah01d1 inc_add_190_23_g424__4547(.A (inc_add_190_23_n_257), .B
       (counts[15]), .CO (inc_add_190_23_n_255), .S (n_119));
  ah01d1 inc_add_190_23_g425__9682(.A (inc_add_190_23_n_259), .B
       (counts[14]), .CO (inc_add_190_23_n_257), .S (n_118));
  ah01d1 inc_add_190_23_g426__2683(.A (inc_add_190_23_n_261), .B
       (counts[13]), .CO (inc_add_190_23_n_259), .S (n_117));
  ah01d1 inc_add_190_23_g427__1309(.A (inc_add_190_23_n_263), .B
       (counts[12]), .CO (inc_add_190_23_n_261), .S (n_116));
  ah01d1 inc_add_190_23_g428__6877(.A (inc_add_190_23_n_265), .B
       (counts[11]), .CO (inc_add_190_23_n_263), .S (n_115));
  ah01d1 inc_add_190_23_g429__2900(.A (inc_add_190_23_n_267), .B
       (counts[10]), .CO (inc_add_190_23_n_265), .S (n_114));
  ah01d1 inc_add_190_23_g430__2391(.A (inc_add_190_23_n_269), .B
       (counts[9]), .CO (inc_add_190_23_n_267), .S (n_113));
  ah01d1 inc_add_190_23_g431__7675(.A (inc_add_190_23_n_271), .B
       (counts[8]), .CO (inc_add_190_23_n_269), .S (n_112));
  ah01d1 inc_add_190_23_g432__7118(.A (inc_add_190_23_n_273), .B
       (counts[7]), .CO (inc_add_190_23_n_271), .S (n_111));
  ah01d1 inc_add_190_23_g433__8757(.A (inc_add_190_23_n_275), .B
       (counts[6]), .CO (inc_add_190_23_n_273), .S (n_110));
  ah01d1 inc_add_190_23_g434__1786(.A (inc_add_190_23_n_277), .B
       (counts[5]), .CO (inc_add_190_23_n_275), .S (n_109));
  ah01d1 inc_add_190_23_g435__5953(.A (inc_add_190_23_n_279), .B
       (counts[4]), .CO (inc_add_190_23_n_277), .S (n_108));
  ah01d1 inc_add_190_23_g436__5703(.A (inc_add_190_23_n_281), .B
       (counts[3]), .CO (inc_add_190_23_n_279), .S (n_107));
  ah01d1 inc_add_190_23_g437__7114(.A (inc_add_190_23_n_283), .B
       (counts[2]), .CO (inc_add_190_23_n_281), .S (n_106));
  ah01d1 inc_add_190_23_g438__5266(.A (counts[0]), .B (counts[1]), .CO
       (inc_add_190_23_n_283), .S (n_105));
  aoi31d1 g2(.A (count[31]), .B1 (n_15), .B2 (n_10), .B3 (n_14), .ZN
       (n_170));
  dfnrb1 uclk_reg(.CP (clk), .D (n_54), .Q (uclk), .QN (n_2));
  dfnrb1 \state_reg[0] (.CP (uclk), .D (n_96), .Q (state[0]), .QN
       (n_1));
  dfnrb1 \count_reg[30] (.CP (clk), .D (n_22), .Q (count[30]), .QN
       (inc_add_153_24_n_419));
  dfnrb1 \count_reg[20] (.CP (clk), .D (n_32), .Q (count[20]), .QN
       (inc_add_153_24_n_429));
  dfnrb1 \count_reg[25] (.CP (clk), .D (n_27), .Q (count[25]), .QN
       (inc_add_153_24_n_437));
  dfnrb1 \count_reg[4] (.CP (clk), .D (n_48), .Q (count[4]), .QN
       (inc_add_153_24_n_445));
  ora211d1 g3379(.A (n_61), .B (inc_add_190_23_n_223), .C1
       (inc_add_190_23_n_226), .C2 (counts[30]), .Z (n_171));
  ora211d1 g3380(.A (n_20), .B (inc_add_153_24_n_405), .C1
       (inc_add_153_24_n_410), .C2 (count[2]), .Z (n_172));
  ora211d1 g3381(.A (n_20), .B (inc_add_153_24_n_373), .C1
       (inc_add_153_24_n_376), .C2 (count[6]), .Z (n_173));
  ora211d1 g3382(.A (n_20), .B (inc_add_153_24_n_349), .C1
       (inc_add_153_24_n_355), .C2 (count[10]), .Z (n_174));
  ora211d1 g3383(.A (n_20), .B (inc_add_153_24_n_335), .C1
       (inc_add_153_24_n_345), .C2 (count[14]), .Z (n_175));
  ora211d1 g3384(.A (n_20), .B (inc_add_153_24_n_332), .C1
       (inc_add_153_24_n_343), .C2 (count[18]), .Z (n_176));
  ora211d1 g3385(.A (n_20), .B (inc_add_153_24_n_323), .C1
       (inc_add_153_24_n_330), .C2 (count[22]), .Z (n_177));
  ora211d1 g3386(.A (n_20), .B (inc_add_153_24_n_347), .C1
       (inc_add_153_24_n_357), .C2 (count[28]), .Z (n_178));
  ora211d1 g3387(.A (n_20), .B (inc_add_153_24_n_320), .C1
       (inc_add_153_24_n_328), .C2 (count[26]), .Z (n_179));
endmodule

module uarttx_clk_freq1000000_baud_rate9600(clk, rst, newd, tx_data,
     tx, donetx);
  input clk, rst, newd;
  input [7:0] tx_data;
  output tx, donetx;
  wire clk, rst, newd;
  wire [7:0] tx_data;
  wire tx, donetx;
  wire [31:0] count;
  wire [31:0] counts;
  wire [7:0] din;
  wire [1:0] state;
  wire inc_add_54_24_n_317, inc_add_54_24_n_318, inc_add_54_24_n_320,
       inc_add_54_24_n_323, inc_add_54_24_n_328, inc_add_54_24_n_330,
       inc_add_54_24_n_332, inc_add_54_24_n_335;
  wire inc_add_54_24_n_338, inc_add_54_24_n_343, inc_add_54_24_n_345,
       inc_add_54_24_n_347, inc_add_54_24_n_349, inc_add_54_24_n_355,
       inc_add_54_24_n_357, inc_add_54_24_n_360;
  wire inc_add_54_24_n_362, inc_add_54_24_n_363, inc_add_54_24_n_367,
       inc_add_54_24_n_369, inc_add_54_24_n_372, inc_add_54_24_n_373,
       inc_add_54_24_n_376, inc_add_54_24_n_378;
  wire inc_add_54_24_n_379, inc_add_54_24_n_381, inc_add_54_24_n_382,
       inc_add_54_24_n_383, inc_add_54_24_n_387, inc_add_54_24_n_388,
       inc_add_54_24_n_392, inc_add_54_24_n_395;
  wire inc_add_54_24_n_400, inc_add_54_24_n_402, inc_add_54_24_n_405,
       inc_add_54_24_n_408, inc_add_54_24_n_409, inc_add_54_24_n_410,
       inc_add_54_24_n_412, inc_add_54_24_n_415;
  wire inc_add_54_24_n_416, inc_add_54_24_n_419, inc_add_54_24_n_429,
       inc_add_54_24_n_437, inc_add_54_24_n_445, inc_add_95_29_n_223,
       inc_add_95_29_n_226, inc_add_95_29_n_229;
  wire inc_add_95_29_n_231, inc_add_95_29_n_233, inc_add_95_29_n_235,
       inc_add_95_29_n_237, inc_add_95_29_n_239, inc_add_95_29_n_241,
       inc_add_95_29_n_243, inc_add_95_29_n_245;
  wire inc_add_95_29_n_247, inc_add_95_29_n_249, inc_add_95_29_n_251,
       inc_add_95_29_n_253, inc_add_95_29_n_255, inc_add_95_29_n_257,
       inc_add_95_29_n_259, inc_add_95_29_n_261;
  wire inc_add_95_29_n_263, inc_add_95_29_n_265, inc_add_95_29_n_267,
       inc_add_95_29_n_269, inc_add_95_29_n_271, inc_add_95_29_n_273,
       inc_add_95_29_n_275, inc_add_95_29_n_277;
  wire inc_add_95_29_n_279, inc_add_95_29_n_281, inc_add_95_29_n_283,
       n_0, n_1, n_2, n_3, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_46, n_47, n_48;
  wire n_50, n_51, n_52, n_54, n_56, n_58, n_59, n_60;
  wire n_62, n_63, n_64, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_154;
  wire n_155, n_156, n_158, n_160, n_161, n_162, n_164, n_165;
  wire n_166, n_168, n_169, n_170, n_172, n_173, n_174, n_176;
  wire n_177, n_178, n_180, n_181, n_182, n_184, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, uclk;
  dfnrq1 \count_reg[0] (.CP (clk), .D (n_54), .Q (count[0]));
  dfnrq1 \count_reg[1] (.CP (clk), .D (n_66), .Q (count[1]));
  dfnrq1 \count_reg[2] (.CP (clk), .D (n_193), .Q (count[2]));
  dfnrq1 \count_reg[3] (.CP (clk), .D (n_69), .Q (count[3]));
  dfnrq1 \count_reg[5] (.CP (clk), .D (n_67), .Q (count[5]));
  dfnrq1 \count_reg[6] (.CP (clk), .D (n_190), .Q (count[6]));
  dfnrq1 \count_reg[7] (.CP (clk), .D (n_64), .Q (count[7]));
  dfnrq1 \count_reg[8] (.CP (clk), .D (n_63), .Q (count[8]));
  dfnrq1 \count_reg[9] (.CP (clk), .D (n_62), .Q (count[9]));
  dfnrq1 \count_reg[10] (.CP (clk), .D (n_191), .Q (count[10]));
  dfnrq1 \count_reg[11] (.CP (clk), .D (n_59), .Q (count[11]));
  dfnrq1 \count_reg[12] (.CP (clk), .D (n_58), .Q (count[12]));
  dfnrq1 \count_reg[13] (.CP (clk), .D (n_60), .Q (count[13]));
  dfnrq1 \count_reg[14] (.CP (clk), .D (n_192), .Q (count[14]));
  dfnrq1 \count_reg[15] (.CP (clk), .D (n_56), .Q (count[15]));
  dfnrq1 \count_reg[16] (.CP (clk), .D (n_70), .Q (count[16]));
  dfnrq1 \count_reg[17] (.CP (clk), .D (n_39), .Q (count[17]));
  dfnrq1 \count_reg[18] (.CP (clk), .D (n_194), .Q (count[18]));
  dfnrq1 \count_reg[19] (.CP (clk), .D (n_52), .Q (count[19]));
  dfnrq1 \count_reg[21] (.CP (clk), .D (n_50), .Q (count[21]));
  dfnrq1 \count_reg[22] (.CP (clk), .D (n_195), .Q (count[22]));
  dfnrq1 \count_reg[23] (.CP (clk), .D (n_48), .Q (count[23]));
  dfnrq1 \count_reg[24] (.CP (clk), .D (n_47), .Q (count[24]));
  dfnrq1 \count_reg[26] (.CP (clk), .D (n_196), .Q (count[26]));
  dfnrq1 \count_reg[27] (.CP (clk), .D (n_42), .Q (count[27]));
  dfnrq1 \count_reg[28] (.CP (clk), .D (n_197), .Q (count[28]));
  dfnrq1 \count_reg[29] (.CP (clk), .D (n_43), .Q (count[29]));
  dfnrq1 \count_reg[31] (.CP (clk), .D (n_40), .Q (count[31]));
  dfnrq1 \counts_reg[0] (.CP (uclk), .D (n_82), .Q (counts[0]));
  dfnrq1 \counts_reg[1] (.CP (uclk), .D (n_110), .Q (counts[1]));
  dfnrq1 \counts_reg[2] (.CP (uclk), .D (n_108), .Q (counts[2]));
  dfnrq1 \counts_reg[3] (.CP (uclk), .D (n_111), .Q (counts[3]));
  dfnrq1 \counts_reg[4] (.CP (uclk), .D (n_109), .Q (counts[4]));
  dfnrq1 \counts_reg[5] (.CP (uclk), .D (n_107), .Q (counts[5]));
  dfnrq1 \counts_reg[6] (.CP (uclk), .D (n_106), .Q (counts[6]));
  dfnrq1 \counts_reg[7] (.CP (uclk), .D (n_105), .Q (counts[7]));
  dfnrq1 \counts_reg[8] (.CP (uclk), .D (n_104), .Q (counts[8]));
  dfnrq1 \counts_reg[9] (.CP (uclk), .D (n_103), .Q (counts[9]));
  dfnrq1 \counts_reg[10] (.CP (uclk), .D (n_102), .Q (counts[10]));
  dfnrq1 \counts_reg[11] (.CP (uclk), .D (n_101), .Q (counts[11]));
  dfnrq1 \counts_reg[12] (.CP (uclk), .D (n_113), .Q (counts[12]));
  dfnrq1 \counts_reg[13] (.CP (uclk), .D (n_100), .Q (counts[13]));
  dfnrq1 \counts_reg[14] (.CP (uclk), .D (n_97), .Q (counts[14]));
  dfnrq1 \counts_reg[15] (.CP (uclk), .D (n_90), .Q (counts[15]));
  dfnrq1 \counts_reg[16] (.CP (uclk), .D (n_98), .Q (counts[16]));
  dfnrq1 \counts_reg[17] (.CP (uclk), .D (n_96), .Q (counts[17]));
  dfnrq1 \counts_reg[18] (.CP (uclk), .D (n_95), .Q (counts[18]));
  dfnrq1 \counts_reg[19] (.CP (uclk), .D (n_94), .Q (counts[19]));
  dfnrq1 \counts_reg[20] (.CP (uclk), .D (n_93), .Q (counts[20]));
  dfnrq1 \counts_reg[21] (.CP (uclk), .D (n_92), .Q (counts[21]));
  dfnrq1 \counts_reg[22] (.CP (uclk), .D (n_91), .Q (counts[22]));
  dfnrq1 \counts_reg[23] (.CP (uclk), .D (n_99), .Q (counts[23]));
  dfnrq1 \counts_reg[24] (.CP (uclk), .D (n_89), .Q (counts[24]));
  dfnrq1 \counts_reg[25] (.CP (uclk), .D (n_88), .Q (counts[25]));
  dfnrq1 \counts_reg[26] (.CP (uclk), .D (n_87), .Q (counts[26]));
  dfnrq1 \counts_reg[27] (.CP (uclk), .D (n_86), .Q (counts[27]));
  dfnrq1 \counts_reg[28] (.CP (uclk), .D (n_85), .Q (counts[28]));
  dfnrq1 \counts_reg[29] (.CP (uclk), .D (n_84), .Q (counts[29]));
  dfnrq1 \counts_reg[30] (.CP (uclk), .D (n_83), .Q (counts[30]));
  dfnrq1 \counts_reg[31] (.CP (uclk), .D (n_188), .Q (counts[31]));
  dfnrq1 \din_reg[0] (.CP (uclk), .D (n_23), .Q (din[0]));
  dfnrq1 \din_reg[1] (.CP (uclk), .D (n_22), .Q (din[1]));
  dfnrq1 \din_reg[2] (.CP (uclk), .D (n_17), .Q (din[2]));
  dfnrq1 \din_reg[3] (.CP (uclk), .D (n_19), .Q (din[3]));
  dfnrq1 \din_reg[4] (.CP (uclk), .D (n_16), .Q (din[4]));
  dfnrq1 \din_reg[5] (.CP (uclk), .D (n_18), .Q (din[5]));
  dfnrq1 \din_reg[6] (.CP (uclk), .D (n_20), .Q (din[6]));
  dfnrq1 \din_reg[7] (.CP (uclk), .D (n_15), .Q (din[7]));
  dfnrq1 \state_reg[1] (.CP (uclk), .D (n_1), .Q (state[1]));
  dfnrq1 tx_reg(.CP (uclk), .D (n_81), .Q (tx));
  aor22d1 g4476__2250(.A1 (n_78), .A2 (n_125), .B1 (rst), .B2
       (counts[12]), .Z (n_113));
  aor22d1 g4478__2703(.A1 (n_78), .A2 (n_116), .B1 (rst), .B2
       (counts[3]), .Z (n_111));
  aor22d1 g4479__5795(.A1 (n_78), .A2 (n_114), .B1 (rst), .B2
       (counts[1]), .Z (n_110));
  aor22d1 g4480__7344(.A1 (n_78), .A2 (n_117), .B1 (rst), .B2
       (counts[4]), .Z (n_109));
  aor22d1 g4481__1840(.A1 (n_78), .A2 (n_115), .B1 (rst), .B2
       (counts[2]), .Z (n_108));
  aor22d1 g4482__5019(.A1 (n_78), .A2 (n_118), .B1 (rst), .B2
       (counts[5]), .Z (n_107));
  aor22d1 g4483__1857(.A1 (n_78), .A2 (n_119), .B1 (rst), .B2
       (counts[6]), .Z (n_106));
  aor22d1 g4484__9906(.A1 (n_78), .A2 (n_120), .B1 (rst), .B2
       (counts[7]), .Z (n_105));
  aor22d1 g4485__8780(.A1 (n_78), .A2 (n_121), .B1 (rst), .B2
       (counts[8]), .Z (n_104));
  aor22d1 g4486__4296(.A1 (n_78), .A2 (n_122), .B1 (rst), .B2
       (counts[9]), .Z (n_103));
  aor22d1 g4487__3772(.A1 (n_78), .A2 (n_123), .B1 (rst), .B2
       (counts[10]), .Z (n_102));
  aor22d1 g4488__1474(.A1 (n_78), .A2 (n_124), .B1 (rst), .B2
       (counts[11]), .Z (n_101));
  aor22d1 g4489__4547(.A1 (n_78), .A2 (n_126), .B1 (rst), .B2
       (counts[13]), .Z (n_100));
  aor22d1 g4493__9682(.A1 (n_136), .A2 (n_78), .B1 (rst), .B2
       (counts[23]), .Z (n_99));
  aor22d1 g4494__2683(.A1 (n_78), .A2 (n_129), .B1 (rst), .B2
       (counts[16]), .Z (n_98));
  aor22d1 g4495__1309(.A1 (n_78), .A2 (n_127), .B1 (rst), .B2
       (counts[14]), .Z (n_97));
  aor22d1 g4496__6877(.A1 (n_130), .A2 (n_78), .B1 (rst), .B2
       (counts[17]), .Z (n_96));
  aor22d1 g4497__2900(.A1 (n_131), .A2 (n_78), .B1 (rst), .B2
       (counts[18]), .Z (n_95));
  aor22d1 g4498__2391(.A1 (n_132), .A2 (n_78), .B1 (rst), .B2
       (counts[19]), .Z (n_94));
  aor22d1 g4499__7675(.A1 (n_133), .A2 (n_78), .B1 (rst), .B2
       (counts[20]), .Z (n_93));
  aor22d1 g4500__7118(.A1 (n_134), .A2 (n_78), .B1 (rst), .B2
       (counts[21]), .Z (n_92));
  aor22d1 g4501__8757(.A1 (n_135), .A2 (n_78), .B1 (rst), .B2
       (counts[22]), .Z (n_91));
  aor22d1 g4502__1786(.A1 (n_78), .A2 (n_128), .B1 (rst), .B2
       (counts[15]), .Z (n_90));
  aor22d1 g4503__5953(.A1 (n_137), .A2 (n_78), .B1 (rst), .B2
       (counts[24]), .Z (n_89));
  aor22d1 g4504__5703(.A1 (n_138), .A2 (n_78), .B1 (rst), .B2
       (counts[25]), .Z (n_88));
  aor22d1 g4505__7114(.A1 (n_139), .A2 (n_78), .B1 (rst), .B2
       (counts[26]), .Z (n_87));
  aor22d1 g4506__5266(.A1 (n_140), .A2 (n_78), .B1 (rst), .B2
       (counts[27]), .Z (n_86));
  aor22d1 g4507__2250(.A1 (n_141), .A2 (n_78), .B1 (rst), .B2
       (counts[28]), .Z (n_85));
  aor22d1 g4508__6083(.A1 (n_142), .A2 (n_78), .B1 (rst), .B2
       (counts[29]), .Z (n_84));
  aor22d1 g4509__2703(.A1 (n_143), .A2 (n_78), .B1 (rst), .B2
       (counts[30]), .Z (n_83));
  mx02d1 g4510__5795(.I0 (n_78), .I1 (rst), .S (counts[0]), .Z (n_82));
  oai211d1 g4512__7344(.A (n_79), .B (n_29), .C1 (n_5), .C2 (newd), .ZN
       (n_81));
  oai21d1 g4513__1840(.A (n_79), .B1 (n_6), .B2 (n_3), .ZN (n_80));
  nd12d0 g4514__5019(.A1 (n_0), .A2 (n_76), .ZN (n_79));
  nr02d0 g4517__9906(.A1 (n_76), .A2 (n_0), .ZN (n_78));
  nr02d0 g4518__8780(.A1 (n_75), .A2 (counts[31]), .ZN (n_76));
  nr04d0 g4519__4296(.A1 (counts[8]), .A2 (counts[10]), .A3
       (counts[9]), .A4 (n_74), .ZN (n_75));
  or04d1 g4520__3772(.A1 (n_73), .A2 (counts[3]), .A3 (counts[14]), .A4
       (counts[12]), .Z (n_74));
  or04d1 g4521__1474(.A1 (n_72), .A2 (counts[29]), .A3 (counts[11]),
       .A4 (counts[7]), .Z (n_73));
  or04d1 g4523__4547(.A1 (n_38), .A2 (counts[22]), .A3 (counts[18]),
       .A4 (counts[20]), .Z (n_72));
  oai22d1 g4540__9682(.A1 (n_189), .A2 (n_2), .B1 (n_36), .B2 (uclk),
       .ZN (n_71));
  an02d1 g4557__2683(.A1 (n_36), .A2 (n_169), .Z (n_70));
  an02d1 g4558__1309(.A1 (n_36), .A2 (n_182), .Z (n_69));
  an02d1 g4559__6877(.A1 (n_36), .A2 (n_181), .Z (n_68));
  an02d1 g4560__2900(.A1 (n_36), .A2 (n_180), .Z (n_67));
  an02d1 g4561__2391(.A1 (n_36), .A2 (n_184), .Z (n_66));
  an02d1 g4563__7118(.A1 (n_36), .A2 (n_178), .Z (n_64));
  an02d1 g4564__8757(.A1 (n_36), .A2 (n_177), .Z (n_63));
  an02d1 g4565__1786(.A1 (n_36), .A2 (n_176), .Z (n_62));
  an02d1 g4567__5703(.A1 (n_36), .A2 (n_172), .Z (n_60));
  an02d1 g4568__7114(.A1 (n_36), .A2 (n_174), .Z (n_59));
  an02d1 g4569__5266(.A1 (n_36), .A2 (n_173), .Z (n_58));
  an02d1 g4571__6083(.A1 (n_36), .A2 (n_170), .Z (n_56));
  nr02d1 g4573__5795(.A1 (count[0]), .A2 (n_189), .ZN (n_54));
  an02d1 g4575__1840(.A1 (n_36), .A2 (n_166), .Z (n_52));
  an02d1 g4576__5019(.A1 (n_36), .A2 (n_165), .Z (n_51));
  an02d1 g4577__1857(.A1 (n_36), .A2 (n_164), .Z (n_50));
  an02d1 g4579__8780(.A1 (n_36), .A2 (n_162), .Z (n_48));
  an02d1 g4580__4296(.A1 (n_36), .A2 (n_161), .Z (n_47));
  an02d1 g4581__3772(.A1 (n_36), .A2 (n_160), .Z (n_46));
  an02d1 g4584__9682(.A1 (n_36), .A2 (n_156), .Z (n_43));
  an02d1 g4585__2683(.A1 (n_36), .A2 (n_158), .Z (n_42));
  an02d1 g4586__1309(.A1 (n_36), .A2 (n_155), .Z (n_41));
  an02d1 g4587__6877(.A1 (n_36), .A2 (n_154), .Z (n_40));
  an02d1 g4588__2900(.A1 (n_36), .A2 (n_168), .Z (n_39));
  or04d1 g4589__2391(.A1 (n_34), .A2 (counts[28]), .A3 (counts[26]),
       .A4 (counts[24]), .Z (n_38));
  inv0d0 g4590(.I (n_189), .ZN (n_36));
  nr04d1 g4592__7118(.A1 (count[25]), .A2 (count[27]), .A3 (count[26]),
       .A4 (n_32), .ZN (n_35));
  or04d1 g4593__8757(.A1 (n_31), .A2 (counts[13]), .A3 (counts[5]), .A4
       (counts[30]), .Z (n_34));
  nr04d1 g4594__1786(.A1 (count[28]), .A2 (count[30]), .A3 (count[29]),
       .A4 (n_30), .ZN (n_33));
  or04d0 g4595__5953(.A1 (n_27), .A2 (count[18]), .A3 (count[19]), .A4
       (count[24]), .Z (n_32));
  or04d1 g4596__5703(.A1 (n_26), .A2 (counts[6]), .A3 (counts[4]), .A4
       (counts[15]), .Z (n_31));
  nd12d1 g4597__7114(.A1 (count[23]), .A2 (n_28), .ZN (n_30));
  aoi22d1 g4598__5266(.A1 (n_7), .A2 (n_24), .B1 (rst), .B2 (tx), .ZN
       (n_29));
  nr04d1 g4599__2250(.A1 (count[17]), .A2 (count[22]), .A3 (count[20]),
       .A4 (n_21), .ZN (n_28));
  nd02d1 g4600__6083(.A1 (n_25), .A2 (n_10), .ZN (n_27));
  or04d1 g4601__2703(.A1 (n_12), .A2 (counts[19]), .A3 (counts[27]),
       .A4 (counts[16]), .Z (n_26));
  nr04d1 g4602__5795(.A1 (count[15]), .A2 (count[16]), .A3 (count[21]),
       .A4 (n_9), .ZN (n_25));
  mx02d1 g4603__7344(.I0 (n_13), .I1 (n_14), .S (counts[0]), .Z (n_24));
  mx02d1 g4612__1840(.I0 (tx_data[0]), .I1 (din[0]), .S (n_8), .Z
       (n_23));
  mx02d1 g4613__5019(.I0 (tx_data[1]), .I1 (din[1]), .S (n_8), .Z
       (n_22));
  nd12d1 g4614__1857(.A1 (count[14]), .A2 (n_11), .ZN (n_21));
  mx02d1 g4615__9906(.I0 (tx_data[6]), .I1 (din[6]), .S (n_8), .Z
       (n_20));
  mx02d1 g4616__8780(.I0 (tx_data[3]), .I1 (din[3]), .S (n_8), .Z
       (n_19));
  mx02d1 g4617__4296(.I0 (tx_data[5]), .I1 (din[5]), .S (n_8), .Z
       (n_18));
  mx02d1 g4618__3772(.I0 (tx_data[2]), .I1 (din[2]), .S (n_8), .Z
       (n_17));
  mx02d1 g4619__1474(.I0 (tx_data[4]), .I1 (din[4]), .S (n_8), .Z
       (n_16));
  mx02d1 g4620__4547(.I0 (tx_data[7]), .I1 (din[7]), .S (n_8), .Z
       (n_15));
  mx04d1 g4621__9682(.I0 (din[1]), .I1 (din[5]), .I2 (din[3]), .I3
       (din[7]), .S0 (counts[2]), .S1 (counts[1]), .Z (n_14));
  mx04d1 g4622__2683(.I0 (din[0]), .I1 (din[4]), .I2 (din[2]), .I3
       (din[6]), .S0 (counts[2]), .S1 (counts[1]), .Z (n_13));
  or04d1 g4623__1309(.A1 (counts[25]), .A2 (counts[17]), .A3
       (counts[23]), .A4 (counts[21]), .Z (n_12));
  nr04d1 g4624__6877(.A1 (count[7]), .A2 (count[13]), .A3 (count[9]),
       .A4 (count[8]), .ZN (n_11));
  oai211d1 g4625__2900(.A (count[4]), .B (count[5]), .C1 (count[2]),
       .C2 (count[3]), .ZN (n_10));
  or04d0 g4626__2391(.A1 (count[10]), .A2 (count[6]), .A3 (count[11]),
       .A4 (count[12]), .Z (n_9));
  nd02d0 g4627__7675(.A1 (n_6), .A2 (newd), .ZN (n_8));
  inv0d0 g4628(.I (n_0), .ZN (n_7));
  inv0d0 g4630(.I (n_6), .ZN (n_5));
  nr02d0 g4631__7118(.A1 (rst), .A2 (state[1]), .ZN (n_6));
  nd12d1 g2__8757(.A1 (n_78), .A2 (n_8), .ZN (n_1));
  nd12d1 g4642__1786(.A1 (rst), .A2 (state[1]), .ZN (n_0));
  oaim22d1 inc_add_54_24_g516__5953(.A1 (inc_add_54_24_n_320), .A2
       (count[27]), .B1 (inc_add_54_24_n_320), .B2 (count[27]), .ZN
       (n_158));
  oaim22d1 inc_add_54_24_g517__5703(.A1 (inc_add_54_24_n_323), .A2
       (count[23]), .B1 (inc_add_54_24_n_323), .B2 (count[23]), .ZN
       (n_162));
  oaim22d1 inc_add_54_24_g518__7114(.A1 (inc_add_54_24_n_317), .A2
       (count[31]), .B1 (inc_add_54_24_n_317), .B2 (count[31]), .ZN
       (n_154));
  oaim22d1 inc_add_54_24_g519__5266(.A1 (inc_add_54_24_n_332), .A2
       (count[19]), .B1 (inc_add_54_24_n_332), .B2 (count[19]), .ZN
       (n_166));
  oaim22d1 inc_add_54_24_g520__2250(.A1 (inc_add_54_24_n_335), .A2
       (count[15]), .B1 (inc_add_54_24_n_335), .B2 (count[15]), .ZN
       (n_170));
  oaim22d1 inc_add_54_24_g521__6083(.A1 (inc_add_54_24_n_349), .A2
       (count[11]), .B1 (inc_add_54_24_n_349), .B2 (count[11]), .ZN
       (n_174));
  oaim22d1 inc_add_54_24_g522__2703(.A1 (inc_add_54_24_n_347), .A2
       (count[29]), .B1 (inc_add_54_24_n_347), .B2 (count[29]), .ZN
       (n_156));
  aoi21d1 inc_add_54_24_g525__1840(.A (inc_add_54_24_n_318), .B1
       (inc_add_54_24_n_338), .B2 (inc_add_54_24_n_419), .ZN (n_155));
  inv0d0 inc_add_54_24_g526(.I (inc_add_54_24_n_317), .ZN
       (inc_add_54_24_n_318));
  nd12d1 inc_add_54_24_g527__5019(.A1 (inc_add_54_24_n_338), .A2
       (count[30]), .ZN (inc_add_54_24_n_317));
  nd02d1 inc_add_54_24_g528__1857(.A1 (inc_add_54_24_n_328), .A2
       (count[26]), .ZN (inc_add_54_24_n_320));
  nd02d1 inc_add_54_24_g529__9906(.A1 (inc_add_54_24_n_330), .A2
       (count[22]), .ZN (inc_add_54_24_n_323));
  ah01d1 inc_add_54_24_g532__3772(.A (inc_add_54_24_n_360), .B
       (count[25]), .CO (inc_add_54_24_n_328), .S (n_160));
  ah01d1 inc_add_54_24_g533__1474(.A (inc_add_54_24_n_362), .B
       (count[21]), .CO (inc_add_54_24_n_330), .S (n_164));
  nd02d1 inc_add_54_24_g534__4547(.A1 (inc_add_54_24_n_343), .A2
       (count[18]), .ZN (inc_add_54_24_n_332));
  nd02d1 inc_add_54_24_g535__9682(.A1 (inc_add_54_24_n_345), .A2
       (count[14]), .ZN (inc_add_54_24_n_335));
  nd03d1 inc_add_54_24_g536__2683(.A1 (inc_add_54_24_n_357), .A2
       (count[29]), .A3 (count[28]), .ZN (inc_add_54_24_n_338));
  ah01d1 inc_add_54_24_g539__6877(.A (inc_add_54_24_n_367), .B
       (count[17]), .CO (inc_add_54_24_n_343), .S (n_168));
  ah01d1 inc_add_54_24_g540__2900(.A (inc_add_54_24_n_369), .B
       (count[13]), .CO (inc_add_54_24_n_345), .S (n_172));
  nd02d1 inc_add_54_24_g542__2391(.A1 (inc_add_54_24_n_357), .A2
       (count[28]), .ZN (inc_add_54_24_n_347));
  nd02d1 inc_add_54_24_g543__7675(.A1 (inc_add_54_24_n_355), .A2
       (count[10]), .ZN (inc_add_54_24_n_349));
  oaim22d1 inc_add_54_24_g544__7118(.A1 (inc_add_54_24_n_373), .A2
       (count[7]), .B1 (inc_add_54_24_n_373), .B2 (count[7]), .ZN
       (n_178));
  ah01d1 inc_add_54_24_g545__8757(.A (inc_add_54_24_n_372), .B
       (count[9]), .CO (inc_add_54_24_n_355), .S (n_176));
  nr02d1 inc_add_54_24_g546__1786(.A1 (inc_add_54_24_n_437), .A2
       (inc_add_54_24_n_363), .ZN (inc_add_54_24_n_357));
  ah01d1 inc_add_54_24_g547__5953(.A (inc_add_54_24_n_379), .B
       (count[24]), .CO (inc_add_54_24_n_360), .S (n_161));
  ah01d1 inc_add_54_24_g548__5703(.A (inc_add_54_24_n_378), .B
       (count[20]), .CO (inc_add_54_24_n_362), .S (n_165));
  nd04d1 inc_add_54_24_g549__7114(.A1 (count[24]), .A2
       (inc_add_54_24_n_379), .A3 (count[27]), .A4 (count[26]), .ZN
       (inc_add_54_24_n_363));
  ah01d1 inc_add_54_24_g550__5266(.A (inc_add_54_24_n_383), .B
       (count[16]), .CO (inc_add_54_24_n_367), .S (n_169));
  ah01d1 inc_add_54_24_g551__2250(.A (inc_add_54_24_n_381), .B
       (count[12]), .CO (inc_add_54_24_n_369), .S (n_173));
  ah01d1 inc_add_54_24_g553__2703(.A (inc_add_54_24_n_387), .B
       (count[8]), .CO (inc_add_54_24_n_372), .S (n_177));
  nd02d1 inc_add_54_24_g554__5795(.A1 (inc_add_54_24_n_376), .A2
       (count[6]), .ZN (inc_add_54_24_n_373));
  ah01d1 inc_add_54_24_g555__7344(.A (inc_add_54_24_n_400), .B
       (count[5]), .CO (inc_add_54_24_n_376), .S (n_180));
  nr02d1 inc_add_54_24_g556__1840(.A1 (inc_add_54_24_n_416), .A2
       (inc_add_54_24_n_382), .ZN (inc_add_54_24_n_378));
  nr03d1 inc_add_54_24_g557__5019(.A1 (inc_add_54_24_n_429), .A2
       (inc_add_54_24_n_395), .A3 (inc_add_54_24_n_382), .ZN
       (inc_add_54_24_n_379));
  nr02d1 inc_add_54_24_g558__1857(.A1 (inc_add_54_24_n_412), .A2
       (inc_add_54_24_n_388), .ZN (inc_add_54_24_n_381));
  inv0d0 inc_add_54_24_g559(.I (inc_add_54_24_n_382), .ZN
       (inc_add_54_24_n_383));
  nd04d1 inc_add_54_24_g560__9906(.A1 (count[12]), .A2
       (inc_add_54_24_n_387), .A3 (inc_add_54_24_n_402), .A4
       (count[13]), .ZN (inc_add_54_24_n_382));
  inv0d0 inc_add_54_24_g561(.I (inc_add_54_24_n_387), .ZN
       (inc_add_54_24_n_388));
  nr02d1 inc_add_54_24_g562__8780(.A1 (inc_add_54_24_n_445), .A2
       (inc_add_54_24_n_392), .ZN (inc_add_54_24_n_387));
  oaim22d1 inc_add_54_24_g563__4296(.A1 (inc_add_54_24_n_405), .A2
       (count[3]), .B1 (inc_add_54_24_n_405), .B2 (count[3]), .ZN
       (n_182));
  nd04d1 inc_add_54_24_g564__3772(.A1 (count[5]), .A2
       (inc_add_54_24_n_409), .A3 (count[7]), .A4 (count[6]), .ZN
       (inc_add_54_24_n_392));
  nd04d1 inc_add_54_24_g565__1474(.A1 (count[21]), .A2
       (inc_add_54_24_n_415), .A3 (count[23]), .A4 (count[22]), .ZN
       (inc_add_54_24_n_395));
  aoi21d1 inc_add_54_24_g566__4547(.A (inc_add_54_24_n_400), .B1
       (inc_add_54_24_n_408), .B2 (inc_add_54_24_n_445), .ZN (n_181));
  nr02d1 inc_add_54_24_g567__9682(.A1 (inc_add_54_24_n_445), .A2
       (inc_add_54_24_n_408), .ZN (inc_add_54_24_n_400));
  nr23d1 inc_add_54_24_g568__2683(.A1 (count[14]), .A2 (count[15]), .A3
       (inc_add_54_24_n_412), .ZN (inc_add_54_24_n_402));
  nd02d1 inc_add_54_24_g570__6877(.A1 (inc_add_54_24_n_410), .A2
       (count[2]), .ZN (inc_add_54_24_n_405));
  inv0d0 inc_add_54_24_g571(.I (inc_add_54_24_n_408), .ZN
       (inc_add_54_24_n_409));
  nd03d1 inc_add_54_24_g572__2900(.A1 (inc_add_54_24_n_410), .A2
       (count[2]), .A3 (count[3]), .ZN (inc_add_54_24_n_408));
  ah01d1 inc_add_54_24_g573__2391(.A (count[0]), .B (count[1]), .CO
       (inc_add_54_24_n_410), .S (n_184));
  nd04d1 inc_add_54_24_g574__7675(.A1 (count[9]), .A2 (count[10]), .A3
       (count[11]), .A4 (count[8]), .ZN (inc_add_54_24_n_412));
  inv0d0 inc_add_54_24_g575(.I (inc_add_54_24_n_416), .ZN
       (inc_add_54_24_n_415));
  nd04d1 inc_add_54_24_g576__7118(.A1 (count[17]), .A2 (count[18]), .A3
       (count[19]), .A4 (count[16]), .ZN (inc_add_54_24_n_416));
  ora21d1 inc_add_95_29_g408__1786(.A (inc_add_95_29_n_223), .B1
       (inc_add_95_29_n_226), .B2 (counts[30]), .Z (n_143));
  nd02d0 inc_add_95_29_g409__5953(.A1 (inc_add_95_29_n_226), .A2
       (counts[30]), .ZN (inc_add_95_29_n_223));
  ah01d1 inc_add_95_29_g410__5703(.A (inc_add_95_29_n_229), .B
       (counts[29]), .CO (inc_add_95_29_n_226), .S (n_142));
  ah01d1 inc_add_95_29_g411__7114(.A (inc_add_95_29_n_231), .B
       (counts[28]), .CO (inc_add_95_29_n_229), .S (n_141));
  ah01d1 inc_add_95_29_g412__5266(.A (inc_add_95_29_n_233), .B
       (counts[27]), .CO (inc_add_95_29_n_231), .S (n_140));
  ah01d1 inc_add_95_29_g413__2250(.A (inc_add_95_29_n_235), .B
       (counts[26]), .CO (inc_add_95_29_n_233), .S (n_139));
  ah01d1 inc_add_95_29_g414__6083(.A (inc_add_95_29_n_237), .B
       (counts[25]), .CO (inc_add_95_29_n_235), .S (n_138));
  ah01d1 inc_add_95_29_g415__2703(.A (inc_add_95_29_n_239), .B
       (counts[24]), .CO (inc_add_95_29_n_237), .S (n_137));
  ah01d1 inc_add_95_29_g416__5795(.A (inc_add_95_29_n_241), .B
       (counts[23]), .CO (inc_add_95_29_n_239), .S (n_136));
  ah01d1 inc_add_95_29_g417__7344(.A (inc_add_95_29_n_243), .B
       (counts[22]), .CO (inc_add_95_29_n_241), .S (n_135));
  ah01d1 inc_add_95_29_g418__1840(.A (inc_add_95_29_n_245), .B
       (counts[21]), .CO (inc_add_95_29_n_243), .S (n_134));
  ah01d1 inc_add_95_29_g419__5019(.A (inc_add_95_29_n_247), .B
       (counts[20]), .CO (inc_add_95_29_n_245), .S (n_133));
  ah01d1 inc_add_95_29_g420__1857(.A (inc_add_95_29_n_249), .B
       (counts[19]), .CO (inc_add_95_29_n_247), .S (n_132));
  ah01d1 inc_add_95_29_g421__9906(.A (inc_add_95_29_n_251), .B
       (counts[18]), .CO (inc_add_95_29_n_249), .S (n_131));
  ah01d1 inc_add_95_29_g422__8780(.A (inc_add_95_29_n_253), .B
       (counts[17]), .CO (inc_add_95_29_n_251), .S (n_130));
  ah01d1 inc_add_95_29_g423__4296(.A (inc_add_95_29_n_255), .B
       (counts[16]), .CO (inc_add_95_29_n_253), .S (n_129));
  ah01d1 inc_add_95_29_g424__3772(.A (inc_add_95_29_n_257), .B
       (counts[15]), .CO (inc_add_95_29_n_255), .S (n_128));
  ah01d1 inc_add_95_29_g425__1474(.A (inc_add_95_29_n_259), .B
       (counts[14]), .CO (inc_add_95_29_n_257), .S (n_127));
  ah01d1 inc_add_95_29_g426__4547(.A (inc_add_95_29_n_261), .B
       (counts[13]), .CO (inc_add_95_29_n_259), .S (n_126));
  ah01d1 inc_add_95_29_g427__9682(.A (inc_add_95_29_n_263), .B
       (counts[12]), .CO (inc_add_95_29_n_261), .S (n_125));
  ah01d1 inc_add_95_29_g428__2683(.A (inc_add_95_29_n_265), .B
       (counts[11]), .CO (inc_add_95_29_n_263), .S (n_124));
  ah01d1 inc_add_95_29_g429__1309(.A (inc_add_95_29_n_267), .B
       (counts[10]), .CO (inc_add_95_29_n_265), .S (n_123));
  ah01d1 inc_add_95_29_g430__6877(.A (inc_add_95_29_n_269), .B
       (counts[9]), .CO (inc_add_95_29_n_267), .S (n_122));
  ah01d1 inc_add_95_29_g431__2900(.A (inc_add_95_29_n_271), .B
       (counts[8]), .CO (inc_add_95_29_n_269), .S (n_121));
  ah01d1 inc_add_95_29_g432__2391(.A (inc_add_95_29_n_273), .B
       (counts[7]), .CO (inc_add_95_29_n_271), .S (n_120));
  ah01d1 inc_add_95_29_g433__7675(.A (inc_add_95_29_n_275), .B
       (counts[6]), .CO (inc_add_95_29_n_273), .S (n_119));
  ah01d1 inc_add_95_29_g434__7118(.A (inc_add_95_29_n_277), .B
       (counts[5]), .CO (inc_add_95_29_n_275), .S (n_118));
  ah01d1 inc_add_95_29_g435__8757(.A (inc_add_95_29_n_279), .B
       (counts[4]), .CO (inc_add_95_29_n_277), .S (n_117));
  ah01d1 inc_add_95_29_g436__1786(.A (inc_add_95_29_n_281), .B
       (counts[3]), .CO (inc_add_95_29_n_279), .S (n_116));
  ah01d1 inc_add_95_29_g437__5953(.A (inc_add_95_29_n_283), .B
       (counts[2]), .CO (inc_add_95_29_n_281), .S (n_115));
  ah01d1 inc_add_95_29_g438__5703(.A (counts[0]), .B (counts[1]), .CO
       (inc_add_95_29_n_283), .S (n_114));
  ora21d1 g2(.A (counts[31]), .B1 (n_187), .B2 (rst), .Z (n_188));
  an02d1 g3(.A1 (inc_add_95_29_n_223), .A2 (state[1]), .Z (n_187));
  aoi21d1 g4644(.A (count[31]), .B1 (n_35), .B2 (n_33), .ZN (n_189));
  dfnrb1 donetx_reg(.CP (uclk), .D (n_80), .Q (donetx), .QN (n_3));
  dfnrb1 uclk_reg(.CP (clk), .D (n_71), .Q (uclk), .QN (n_2));
  dfnrb1 \count_reg[30] (.CP (clk), .D (n_41), .Q (count[30]), .QN
       (inc_add_54_24_n_419));
  dfnrb1 \count_reg[20] (.CP (clk), .D (n_51), .Q (count[20]), .QN
       (inc_add_54_24_n_429));
  dfnrb1 \count_reg[25] (.CP (clk), .D (n_46), .Q (count[25]), .QN
       (inc_add_54_24_n_437));
  dfnrb1 \count_reg[4] (.CP (clk), .D (n_68), .Q (count[4]), .QN
       (inc_add_54_24_n_445));
  ora211d1 g4657(.A (n_36), .B (inc_add_54_24_n_373), .C1
       (inc_add_54_24_n_376), .C2 (count[6]), .Z (n_190));
  ora211d1 g4658(.A (n_36), .B (inc_add_54_24_n_349), .C1
       (inc_add_54_24_n_355), .C2 (count[10]), .Z (n_191));
  ora211d1 g4659(.A (n_36), .B (inc_add_54_24_n_335), .C1
       (inc_add_54_24_n_345), .C2 (count[14]), .Z (n_192));
  ora211d1 g4660(.A (n_36), .B (inc_add_54_24_n_405), .C1
       (inc_add_54_24_n_410), .C2 (count[2]), .Z (n_193));
  ora211d1 g4661(.A (n_36), .B (inc_add_54_24_n_332), .C1
       (inc_add_54_24_n_343), .C2 (count[18]), .Z (n_194));
  ora211d1 g4662(.A (n_36), .B (inc_add_54_24_n_323), .C1
       (inc_add_54_24_n_330), .C2 (count[22]), .Z (n_195));
  ora211d1 g4663(.A (n_36), .B (inc_add_54_24_n_320), .C1
       (inc_add_54_24_n_328), .C2 (count[26]), .Z (n_196));
  ora211d1 g4664(.A (n_36), .B (inc_add_54_24_n_347), .C1
       (inc_add_54_24_n_357), .C2 (count[28]), .Z (n_197));
endmodule

module uart_top(clk, rst, rx, dintx, newd, tx, doutrx, donetx, donerx);
  input clk, rst, rx, newd;
  input [7:0] dintx;
  output tx, donetx, donerx;
  output [7:0] doutrx;
  wire clk, rst, rx, newd;
  wire [7:0] dintx;
  wire tx, donetx, donerx;
  wire [7:0] doutrx;
  uartrx_clk_freq1000000_baud_rate9600 rtx(clk, rst, rx, donerx,
       doutrx);
  uarttx_clk_freq1000000_baud_rate9600 utx(clk, rst, newd, dintx, tx,
       donetx);


//////////////////////////////////////
/////////////////////////////////////
/////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////
/// clock and reset pin instantation
pc3d01 Frst(.PAD(rst),.CIN(rst));
pc3c01 Fclk(.CCLK(clk),.CP(clk1));
//input data line
pc3d01 dintx7(.PAD(dintx[7]),.CIN(dintx[7]));
pc3d01 dintx6(.PAD(dintx[6]),.CIN(dintx[6]));
pc3d01 dintx5(.PAD(dintx[5]),.CIN(dintx[5]));
pc3d01 dintx4(.PAD(dintx[4]),.CIN(dintx[4]));
pc3d01 dintx3(.PAD(dintx[3]),.CIN(dintx[3]));
pc3d01 dintx2(.PAD(dintx[2]),.CIN(dintx[2]));
pc3d01 dintx1(.PAD(dintx[1]),.CIN(dintx[1]));
pc3d01 dintx0(.PAD(dintx[0]),.CIN(dintx[0]));
//output data line
pc3d01 doutrx7(.PAD(doutrx[7]),.CIN(doutrx[7]));
pc3d01 doutrx6(.PAD(doutrx[6]),.CIN(doutrx[6]));
pc3d01 doutrx5(.PAD(doutrx[5]),.CIN(doutrx[5]));
pc3d01 doutrx4(.PAD(doutrx[4]),.CIN(doutrx[4]));
pc3d01 doutrx3(.PAD(doutrx[3]),.CIN(doutrx[3]));
pc3d01 doutrx2(.PAD(doutrx[2]),.CIN(doutrx[2]));
pc3d01 doutrx1(.PAD(doutrx[1]),.CIN(doutrx[1]));
pc3d01 doutrx0(.PAD(doutrx[0]),.CIN(doutrx[0]));
//control line
pc3d01 Frx(.PAD(rx),.CIN(rx));
pc3d01 Fnewd(.PAD(newd),.CIN(newd));
//status signal
pc3d01 Ftx(.PAD(tx),.CIN(tx));
pc3d01 Fdonetx(.PAD(donetx),.CIN(donetx));
pc3d01 Fdonerx(.PAD(donerx),.CIN(donerx));



endmodule

