//**************************************************
//*                                                
//* Copyright (C) 2010 Cadence Design Systems, Inc.
//* All rights reserved.
//*
//* LEC SCRIPT FILE: runLECDir/runLEC.do
//* GENERATED BY   : runLEC -golden ../rtl/uart.v -revised ../synthesis/UART_netlist.v
//* ENCOUNTER      : 17.12-s095_1
//* TIME GENERATED : 12/28/2023 13:18:59
//*
//* NOTE: Requires Conformal Logic Equivalence Checking
//*       Release 08.10 or later
//*
//**************************************************

//***********************************************
// set up log file, get misc info about the run
//***********************************************
set log file runLECDir/runLEC.log -replace
version
hostname
date
pwd
usage
set dofile abort off
set undefined cell Black_box
set rule handling -limit 1000 *


//***********************************************
// read library in verilog or liberty format
// by default libraries are used for both golden and revised designs
//***********************************************
// Copy paste of the below multiple lines fails, can use the following one line instead
// read library -both -liberty -statetable  /home/vlsi1/Downloads/scl_pdk/stdlib/fs120/liberty/lib_flow_ss/tsl18fs120_scl_ss.lib /home/vlsi1/Downloads/scl_pdk/iolib/cio250/synopsys/2002.05/models/tsl18cio250_max.lib /home/vlsi1/Downloads/scl_pdk/stdlib/fs120/liberty/lib_flow_ff/tsl18fs120_scl_ff.lib /home/vlsi1/Downloads/scl_pdk/iolib/cio250/synopsys/2002.05/models/tsl18cio250_min.lib  

read library -both -liberty -statetable  /home/vlsi1/Downloads/scl_pdk/stdlib/fs120/liberty/lib_flow_ss/tsl18fs120_scl_ss.lib \
   /home/vlsi1/Downloads/scl_pdk/iolib/cio250/synopsys/2002.05/models/tsl18cio250_max.lib \
   /home/vlsi1/Downloads/scl_pdk/stdlib/fs120/liberty/lib_flow_ff/tsl18fs120_scl_ff.lib \
   /home/vlsi1/Downloads/scl_pdk/iolib/cio250/synopsys/2002.05/models/tsl18cio250_min.lib \
    


//***********************************************
// check if reading the library was smooth
//***********************************************
report rule check -library
usage


//***********************************************
// read golden and revised design
//***********************************************
read design -golden   ../rtl/uart.v   -verilog 
read design -revised  ../synthesis/UART_netlist.v   -verilog 


//***********************************************
// check if designs are clean + report design data
//***********************************************
report design data
report black box
// report module
report floating signal
usage


//***********************************************
// flattening and mapping
//***********************************************
set system mode lec
report mapped point -summary
report unmapped point
usage


//***********************************************
// compare mapped key points
//***********************************************
add compare point -all
compare
usage


//***********************************************
// report compare result
//***********************************************
// report compare data -eq
report compare data -noneq
report compare data -abort
report compare data -verbose > runLECDir/comparison.rpt


//***********************************************
// print summary 
//***********************************************
set command echo off
echo
echo "==============================================================================="
echo "=            Netlist Comparison Summary    "
echo "==============================================================================="
report compare data -summary
echo
echo
echo " Info: Generated netlist comparison report:"
echo "       runLECDir/comparison.rpt"
echo
set command echo on
usage


//***********************************************
// start GUI
//***********************************************
// set gui on

//***********************************************
// exit LEC
//***********************************************
exit -Force -Success
